#!/usr/bin/env python
import sys


    
differences = 0
    

try:
    file1 = open(sys.argv[1])
except:
    print("file1wontopen")
try:
    file2 = open(sys.argv[2])
except:
    print("file2wontopen")


#broken1 = ([*file1])

#for line_f1, line_f2 in zip(file1, file2):


my_list1 = ['a', 2, 'c']
my_list2 = [1, 'b', 3]

print(zip(my_list1, my_list2))

#[('a', 1), (2, 'b'), ('c', 3)]

#line_f1, line_f2 = ('a', 1)